[package]
name = "vcfgrpaf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
rust-htslib = "0.44"          # 需系统有 libhts
csv = "1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
crossbeam = "*"